# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-14 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название категории')),
                ('title_plural', models.CharField(db_index=True, max_length=50, verbose_name='Название категории во множественном числе')),
                ('item_count', models.IntegerField(blank=True, null=True, verbose_name='Количесвто товаров в категории')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Цвет')),
                ('code', models.CharField(max_length=25, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=150, verbose_name='Текст комментария')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Название детали')),
                ('price', models.IntegerField(verbose_name='Закупочная цена')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('image', models.ImageField(blank=True, upload_to='details/%Y/%m/%d/')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AppSklad.Category', verbose_name='Категория детали')),
                ('color', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AppSklad.Color', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название модели')),
                ('price', models.IntegerField(verbose_name='Отпускная цена')),
                ('expenses', models.IntegerField(blank=True, null=True, verbose_name='Затраты на изготовление')),
                ('available', models.IntegerField(blank=True, null=True, verbose_name='Количетсво достпных')),
                ('profit', models.IntegerField(blank=True, null=True, verbose_name='Прибыль')),
                ('image', models.ImageField(blank=True, upload_to='items/%Y/%m/%d/')),
                ('publicate', models.BooleanField(db_index=True, default=False, verbose_name='Публикация')),
                ('author', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AppSklad.Category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_count', models.IntegerField(verbose_name='Количество деталей')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AppSklad.Detail', verbose_name='Деталь')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemdetails', to='AppSklad.Item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Деталь товара',
                'verbose_name_plural': 'Детали товаров',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('register_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('last_seen', models.DateField(blank=True, null=True, verbose_name='Дата последнего посещения')),
                ('remember', models.BooleanField(default=False, verbose_name='Запомнить')),
                ('image', models.ImageField(blank=True, upload_to='avatars/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='AppSklad.Item', verbose_name='Товар'),
        ),
    ]
