# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-12 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSklad', '0003_auto_20170112_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
