# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-13 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppSklad', '0005_auto_20170114_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='color',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AppSklad.Color', verbose_name='Цвет'),
        ),
    ]
