# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-14 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppSklad', '0008_auto_20170115_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSklad.Item', verbose_name='Товар'),
        ),
    ]
