# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-15 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSklad', '0014_auto_20170116_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='publicate',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
