# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-27 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSklad', '0017_auto_20170116_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего посещения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='register_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='profile',
            name='remember',
            field=models.BooleanField(default=False, verbose_name='Запомнить'),
        ),
    ]
