# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-12 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSklad', '0018_auto_20170127_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title_plural',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название категории во множественном числе'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название детали'),
        ),
        migrations.AlterField(
            model_name='item',
            name='publicate',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название модели'),
        ),
    ]
